### PR TITLE
Axes position

### PR DESCRIPTION
**Pull request by natalia-zolochevska**

### CODE REVIEW

**Comment by alexpreynolds** [comment]
Nice start! Please see the following snapshot:

https://dl.dropboxusercontent.com/u/31495717/cubemaker/082515_122233.png

This cube orientation should show two axes in the face that is directly facing the viewer/camera. It looks like a "hidden" axis is highlighted, instead.

**Comment by alexpreynolds** [comment]
Also, this branch is not up-to-date with the base `gh-pages` branch. For instance, double-tapping all the arrow keys does not trigger the expected animation, so it looks like some commits are missing from the `axes` branch. 

Please double-check and make sure that all your pull requests are in sync with the current state of `gh-pages`.

Also, please let me know when I can look at the other pull requests once they are in sync, so that I can start merging completed features into the main branch. If the PRs are not in sync, it is a lot harder for me to merge features.

Let me know if you have any questions.

**Comment by natalia-zolochevska** [comment]
Resolved an issue for screenshot shared, updated with the latest commits from gh_pages

**Comment by alexpreynolds** [comment]
This looks better, thanks. 

In the future, a settings panel might contain a checkbox for turning axes display on and off.

I have added a change to `gh_pages` to include a flag in the cube data called `show_axes` that sets whether the axes are displayed or not:

```
var sample = {
  "metadata" : {
    ...
    "show_axes" : false,
    ...
  }
}
```

Can you please merge changes from `gh-pages` into the `axes` branch, change this flag's value from `false` to `true` and add code to check the state of this flag and display the axes?

**Comment by natalia-zolochevska** [comment]
I've merged changes from gh-pages into the axes branch, changed this flag's value from false to true and added code to check the state of this flag and display the axes

**Comment by alexpreynolds** [comment]
If I compare mouseovers on data points in the `gh-pages` branch and the `axes` branch, it looks like the data point labels are not shown in the correct position. Can you take a look and see if you see the same thing?

**Comment by alexpreynolds** [comment]
I think this reintroduces the bug in https://github.com/alexpreynolds/cubemaker/issues/16 

Can you test and see if this happens for you as well?

**Comment by alexpreynolds** [comment]
I have updated `gh-pages` with a settings panel (click on the "gear" in the top-left corner of the screen to open). 

Can you please merge `gh-pages` into the `axes` branch and after testing if things work, enable the settings switch, in order to turn the display of axes on or off?

**Comment by natalia-zolochevska** [comment]
I've merged gh-pages into the axes branch and added a handler for settings switch to turn the display of axes on or off

**Comment by alexpreynolds** [comment]
Looks good. Can you start looking into adding axis tick marks and numerical labels? 

Depending on the length of the axis, a short axis might show two numerical labels (min and max range over the axis). A long axis might show four or five (min and max, and two or three values in between).

**Comment by alexpreynolds** [comment]
We seem to be missing the `gh-pages` branch. Were there changes you made that might have accidentally deleted this branch?

**Comment by alexpreynolds** [comment]
We seem to be missing the gh-pages branch. Were there changes you made that
might have accidentally deleted this branch?

**Comment by natalia-zolochevska** [comment]
I noticed that when was updating from the repo, but didn't realised it was
me who deleted the branch. Didn't mean that. Axes currently is a default
branch. I will resolve this tomorrow. Sorry about that.

## Natalia

Natalia Zolochevska

Software Developer | Enterprise Technologies | TeamDev, Ltd.
Phone: +380 57 766-0163 x 2017

Natalia.Zolochevska@teamdev.com | www.teamdev.com

If you have been sent this email in error, please forward it to mismail @
teamdev.com and delete the original. Any opinions expressed within email
are those of the sender and do not necessarily represent the official
opinion of TeamDev Ltd.

**Comment by alexpreynolds** [comment]
Okay, thanks for getting back to me. I couldn't tell from the commit
history what happened. I have a local backup (I think), so let me know if
we need it.

**Comment by natalia-zolochevska** [comment]
Hi Alex,

Your local copy would be helpful. I don't see a straightforward way to
restore that branch.
Sorry for not replying to your for a long time, I'm working on ticks and
labels, but were absent for several days do too my sickness (just regular
autumn cold). I will come back soon with implementation and fixes.

Regards,
Natalia

Natalia Zolochevska

Software Developer | Enterprise Technologies | TeamDev, Ltd.
Phone: +380 57 766-0163 x 2017

Natalia.Zolochevska@teamdev.com | www.teamdev.com

If you have been sent this email in error, please forward it to mismail @
teamdev.com and delete the original. Any opinions expressed within email
are those of the sender and do not necessarily represent the official
opinion of TeamDev Ltd.

**Comment by alexpreynolds** [comment]
Sorry you're not feeling well. I have added a branch called 'gh-pages' that
I think should be at the state before it was removed. I also reset the
default branch back to 'gh-pages'. I think we should be able to proceed
onwards, when you're feeling better.

Thanks,
Alex

**Pull request closed without merging**
